apiVersion: v1
kind: Secret
metadata:
  name: student-db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: studentdb
  MYSQL_USER: studentuser
  MYSQL_PASSWORD: studentpass